#!/usr/bin/env ruby

blacklist = %w(. .. .git .gitignore go-time README.md)
home = ENV["HOME"]+"/"

Dir.foreach(home+".dotfiles") do |item|
  next if blacklist.include? item
  home_file = home+".#{item}"
  if File.exists?(home_file)
    File.delete(home_file)
    puts "Deleting #{item} and re-linking"
  else
    puts "symlinking #{ item }"
  end
  File.symlink("#{home+".dotfiles"}/#{item}", home+".#{ item }")
end
