alias am="git commit --amend"
alias b="git branch --verbose"
alias co="git checkout"
alias cob="git checkout -b"
alias d="git diff"
alias dc="git --no-pager diff --cached"
alias l="git log"
alias reset="git reset HEAD --hard"
alias s="git status"

